### PR TITLE
Fixes for latest clippy warnings

### PR DESCRIPTION
**Pull request by nils-ohlmeier**

### CODE REVIEW

**Comment by nils-ohlmeier** [comment]
This should fix the clippy warnings encountered in #262 CI run.

**Comment by nils-ohlmeier** [comment]
Looks like Travis has trouble with macOS machines.... :-(

**Comment by SE2Dev** [comment]
I can confirm that this builds for me on an M1 Mac running Monterey, so it probably really is just some sort of configuration issue with Travis-CI.

**Comment by nils-ohlmeier** [comment]
I think PR #270 super seeds this.

**Pull request closed without merging**
