### PR TITLE
Add additional allowed sdp payload types to parse_media.

### PR DESCRIPTION
**Pull request by mjfroman**
See https://tools.ietf.org/html/rfc3551#section-6
and https://tools.ietf.org/html/rfc5761#section-4

### CODE REVIEW

**Review by na-g — CHANGES_REQUESTED** [review]
Thanks for the patch. Can you check that we do something sane in Fx with format numbers for formats we don't support? We had traditionally tried to eliminate adding code that would produce cold paths in Fx.

**Review by na-g — APPROVED** [review]

**Comment by nils-ohlmeier** [comment]
I'm okay with the parser accepting all assigned values, minus what @na-g said making sure Firefox does something sane. But I'm not sure why the parser should accept the unassinged values as well?

**Comment by sinduvi87** [comment]
Any plans of merging this PR?

**Comment by sinduvi87** [comment]
@na-g @nils-ohlmeier Just wondering if I should create a separate PR for adding support for additional payload types to parse_media or if there are any plans of merging this PR?

**Pull request closed without merging**
