### PR TITLE
Added set_connection_force method

### PR DESCRIPTION
**Pull request by Mnwa**
Hey! That's PR relates to [this issue](https://github.com/mozilla/webrtc-sdp/issues/221). 
I've added the `set_connection_force` method, which doesn't check on an existing connection.

### CODE REVIEW

**Comment by na-g** [comment]
@mnwa, thanks for the patch! I think there are two issues at play here. The API wasn't really designed from the start to be manually manipulated, and that the check for duplicate connections at parse time is happening in `set_connection` instead of where the media section is being parsed. @Mnwa, I would be happier with moving the check that is in `set_connection` to before `set_connection` is being called in the parser removing the need for another method. @nils-ohlmeier , do you have thoughts otherwise?

**Comment by Mnwa** [comment]
I checked usages of the `set_connection` method and think what that's check need only on `parse_media_vector` when we parse media lines. Maybe move that check to `parse_media_vector`?

**Comment by na-g** [comment]
> I checked usages of the `set_connection` method and think what that's check need only on `parse_media_vector` when we parse media lines. Maybe move that check to `parse_media_vector`?

@Mnwa, that sounds good to me.

**Comment by nils-ohlmeier** [comment]
Indeed that is probably the better solution long term.

**Comment by Mnwa** [comment]
Done. Also, I can change the `set_connection` signature and remove useless `Result<(), SdpParserInternalError>`, but it can break backward compatibility.

**Comment by na-g** [comment]
> Done. Also, I can change the `set_connection` signature and remove useless `Result<(), SdpParserInternalError>`, but it can break backward compatibility.

Go ahead and remove it. I will bump the version number and cut a new release.

**Comment by Mnwa** [comment]
Done

**Pull request merged**
